source "file://#{File.expand_path('../../../../gem_dependencies', __FILE__)}"
# source :rubygems

gem 'jruby-openssl', :platforms => :jruby
gem 'rails', '3.2.3'
gem 'activerecord-jdbc-adapter', '~> 1.2.2', :platforms => :jruby

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'activeadmin'
gem 'omniauth-facebook'
gem 'omniauth-twitter'

group :development do
  gem 'sqlite3', :platforms => :ruby
  gem 'activerecord-jdbcsqlite3-adapter', :platforms => :jruby
end
group :derby do
  gem 'activerecord-jdbcderby-adapter', :platforms => :jruby
end
group :production do
  gem 'pg', :platforms => :ruby
  gem 'activerecord-jdbcpostgresql-adapter', :platforms => :jruby
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby
  gem 'therubyrhino', :platforms => :jruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
